### ISSUE TITLE
Unable to roll initiative in PF2E

### ISSUE THREAD

**Issue by nguyenjessev** [kakaroto/fvtt-module-lmrtfy#183]
### Description
When I request an initiative roll from a player, nothing happens on their end when they click "Initiative" in their popup window. Tried this on a fresh world where LMRTFY was the only active module

### Steps to reproduce
Start a new world, set up a dummy user and actor, activate LMRTFY. Request an initiative roll from the dummy user/actor, then in another window try to click the "Initiative" button in the popup.

### Expected behavior
Initiative is rolled

### Actual behavior
In the console, there is an error on line 352 saying that `skill` is undefined
https://github.com/League-of-Foundry-Developers/fvtt-module-lmrtfy/blob/024c88b65f1c92a3be691bac3fc94c84a5bd8a4b/src/roller.js#L352

Possibly related, I noticed that the `initiative` object does not have an `ability` property, just a `statistic` property. Not sure if it's related though because I tried changing line 351 but then got a new error on line 356 saying that `initiative.roll` is not a function
https://github.com/League-of-Foundry-Developers/fvtt-module-lmrtfy/blob/024c88b65f1c92a3be691bac3fc94c84a5bd8a4b/src/roller.js#L351
https://github.com/League-of-Foundry-Developers/fvtt-module-lmrtfy/blob/024c88b65f1c92a3be691bac3fc94c84a5bd8a4b/src/roller.js#L356

**Comment by nethershaw** [comment]
Same -- but for _all_ skills and abilities with the latest pf2e system on FVTT 11 Stable:

```js
roller.js:287 Uncaught (in promise) TypeError: skill.roll is not a function
    at LMRTFYRoller._makeRoll (roller.js:287:35)
    at LMRTFYRoller._onSkillCheck (roller.js:541:18)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
```

If you don't intend to support Pathfinder systems, _say so._ Broken support is worse than no support.

**Comment by nethershaw** [comment]
This fork contains fixes -- only for pf2e -- that the author hasn't bothered to upstream. You might consider working together. Or communicating.

https://github.com/iBoMbY/fvtt-module-lmrtfy

**Comment by Imper1um** [comment]
I wasn't entirely sure how pf2e rolls initiative, but I did repair the functionality. The lmrtfy-pf2e module that was made is so far separated from this version now that merging the two would require a major amount of changes. I updated the Initiative check on PR #189

**Comment by nethershaw** [comment]
@Varriount @vtt-lair Maintain this repository or find someone else to do it.
